# exercise_one
prueba funcional con tkinter caso_1 
el resgitro fue fangda....
